apiVersion: v1
kind: Namespace
metadata:
  name: tenant
  labels:
    platform.local/vendor: placeholder
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
