apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: objects
spec:
  hard:
    configmaps: "50"
    secrets: "50"
    services: "20"
    services.loadbalancers: "0"
    count/routes.route.openshift.io: "10"
